apiVersion: v1
kind: Service
metadata:
  name: tartarian-api-service
spec:
  selector:
    app: tartarian-api
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer
